apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: media-nfs
  storageClassName: ""
