---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-media
  namespace: pinchflat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: pinchflat-media-nfs
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-config
  namespace: pinchflat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1.5Gi
