apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: onepassword-service-account
  namespace: onepassword-operator
spec:
  itemPath: "vaults/Secrets/items/1Password Service Account"
