injector:
  customEnvVars:
    - name: OP_SERVICE_ACCOUNT_TOKEN
      valueFrom:
        secretKeyRef:
          name: onepassword-service-account
          namespace: onepassword-operator
          key: token
