---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  namespace: emby
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media
  namespace: emby
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  volumeName: emby-media-nfs
  storageClassName: ""
